# -*- coding: utf-8 -*-
"""Project 1 & 2 (decodelabs Internship).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMbwYNgaRYsSX4wI6_19S8ePC2cQCiOQ
"""

import pandas as pd
import numpy as np
df=pd.read_excel("/content/drive/MyDrive/Online-Store-Orders.xlsx")
df.shape
df.head()

df.info()

"""# **Check Missing value**"""

df.isnull().sum()

"""# **Handle Missing Value**"""

df['CouponCode'] = df['CouponCode'].fillna('NoCoupon')

print("Check Missing Values of CouponCode")
print(df['CouponCode'].isnull().sum())

# 3. Numerical data ka statistical summary check karein (outliers dekhne ke liye)
print("\nNumerical Columns Ka Summary Statistics ")
print(df[['Quantity', 'UnitPrice', 'TotalPrice']].describe())

"""**Feature Engineering (Creating 3 New Features)**"""

df['Date'] = pd.to_datetime(df['Date'])

# 1. Feature 1: DiscountApplied (Binary: 1 if coupon used, 0 otherwise)
df['DiscountApplied'] = df['CouponCode'].apply(lambda x: 0 if x == 'NoCoupon' else 1)

# 2. Feature 2: PricePerItemInCart
df['PricePerItemInCart'] = df['TotalPrice'] / df['ItemsInCart']

# 3. Feature 3: IsWeekend (Saturday=5, Sunday=6)
df['IsWeekend'] = df['Date'].dt.dayofweek.apply(lambda x: 1 if x >= 5 else 0)

# Naye features ko verify karne ke liye data ka preview check karein
print("Naye Engineered Features Ka Preview ")
print(df[['CouponCode', 'DiscountApplied', 'TotalPrice', 'ItemsInCart', 'PricePerItemInCart', 'Date', 'IsWeekend']].head())

print("\nDataframe Ke Saare Columns Ki List ")
print(df.columns.tolist())

"""# **Outliers**"""

# 1. Q1 (25th percentile) aur Q3 (75th percentile) calculate karein
Q1 = df['TotalPrice'].quantile(0.25)
Q3 = df['TotalPrice'].quantile(0.75)
IQR = Q3 - Q1

# 2. Lower aur Upper bounds set karein
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# 3. Outliers identify karein
outliers = df[(df['TotalPrice'] < lower_bound) | (df['TotalPrice'] > upper_bound)]

print(f" Outliers Ki Summary ")
print(f"Q1 (25%): {Q1}")
print(f"Q3 (75%): {Q3}")
print(f"IQR: {IQR}")
print(f"Lower Bound: {lower_bound}")
print(f"Upper Bound: {upper_bound}")
print(f"Total Outliers Milay: {len(outliers)}")

if len(outliers) > 0:
    print("\n Kuch Outliers Ka Preview")
    print(outliers[['OrderID', 'TotalPrice']].head())

import matplotlib.pyplot as plt
import seaborn as sns

# Graph ka size set karein
plt.figure(figsize=(8, 5))

# TotalPrice ka Box Plot banayein
sns.boxplot(x=df['TotalPrice'], color='lightblue')

# Title aur labels add karein
plt.title('Outliers Identification in TotalPrice (Box Plot)', fontsize=14)
plt.xlabel('TotalPrice ($)', fontsize=12)

# Graph show karein
plt.show()

"""# **Data Normalization**"""

from sklearn.preprocessing import MinMaxScaler

# 1. MinMaxScaler ka object banayein
scaler = MinMaxScaler()

# 2. TotalPrice column ko 0-1 ke beech scale karein
# (reshape isliye zaroori hai kyunki scaler 2D array expect karta hai)
df['TotalPrice_Scaled'] = scaler.fit_transform(df[['TotalPrice']])

# 3. Scaling verify karne ke liye summary statistics check karein
print("--- Scaling Ke Baad Summary Statistics --")
print(df[['TotalPrice', 'TotalPrice_Scaled']].describe())

# Preview dekhne ke liye
print("\n Original vs Scaled Price Preview ")
print(df[['TotalPrice', 'TotalPrice_Scaled']].head())

# 1. Jin categorical columns ko encode karna hai unki list
categorical_cols = ['Product', 'PaymentMethod', 'ReferralSource']

# 2. One-Hot Encoding apply karein (True/False ki jagah 1/0 ke liye dtype=int lagaya hai)
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True, dtype=int)

# 3. Purane unneeded text/ID columns ko drop karein jo model mein use nahi hote
columns_to_drop = ['OrderID', 'CustomerID', 'ShippingAddress', 'OrderStatus', 'TrackingNumber', 'Date', 'CouponCode']
df_final = df_encoded.drop(columns=columns_to_drop)

print("Final Dataset Ke Columns")
print(df_final.columns.tolist())

# 4. Final cleaned dataset ko aik naye CSV file mein save karein
df_final.to_csv('Cleaned_Online_Store_Orders.csv', index=False)
print("\n Congratulation ! Successfuly Save Cleaned dataset 'Cleaned_Online_Store_Orders.csv' ")

"""# **Project 2 (Task)**"""

from sklearn.model_selection import train_test_split

# 1. Features (X) aur Target (y) alag karein
# Hum 'DiscountApplied' ko target variable bana kar classify karna seekhte hain
X = df_final.drop(columns=['DiscountApplied'])
y = df_final['DiscountApplied']

# 2. Data ko Train aur Test sets mein split karein (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("--- Train aur Test Set Ka Size ---")
print(f"X_train Size: {X_train.shape}")
print(f"X_test Size: {X_test.shape}")

print("\n--- Target Variable Mein Classes Ki Distribution (Train Set) ---")
print(y_train.value_counts())

from imblearn.over_sampling import SMOTE

# 1. SMOTE ka object banayein
smote = SMOTE(random_state=42)

# 2. Sirf Train Data par SMOTE apply karein (Data Leakage se bachne ke liye)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print("After Applying SMOTE ")
print(f"Resampled X_train Size: {X_train_res.shape}")
print(f"Resampled y_train Size: {y_train_res.shape}")

print("\nTarget Variable Ki New Distribution ")
print(y_train_res.value_counts())

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# 1. Logistic Regression model ko initialize aur train karein
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_res, y_train_res)

# 2. Random Forest model ko initialize aur train karein
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_res, y_train_res)

# 3. Dono models se Test set par predictions lein
y_pred_lr = lr_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)

# 4. Prediction probabilities bhi nikalen (ROC-AUC score ke liye)
y_prob_lr = lr_model.predict_proba(X_test)[:, 1]
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("Mubarak ho! Dono models successfully train ho gaye hain aur predictions generate ho chuki hain.")

from sklearn.metrics import classification_report, roc_auc_score

# 1. Logistic Regression ki performance evaluation
print("================ LOGISTIC REGRESSION REPORT ================")
print(classification_report(y_test, y_pred_lr))
print(f"Logistic Regression ROC-AUC Score: {roc_auc_score(y_test, y_prob_lr):.4f}\n")

# 2. Random Forest ki performance evaluation
print("================   RANDOM FOREST REPORT   ================")
print(classification_report(y_test, y_pred_rf))
print(f"Random Forest ROC-AUC Score: {roc_auc_score(y_test, y_prob_rf):.4f}")

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

# 1. Dono models ke liye False Positive Rate (fpr) aur True Positive Rate (tpr) nikalen
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)

# 2. Graph plot karein
plt.figure(figsize=(8, 6))
plt.plot(fpr_lr, tpr_lr, label=f'Logistic Regression (AUC = {roc_auc_score(y_test, y_prob_lr):.4f})')
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_score(y_test, y_prob_rf):.4f})', color='green')

# Baseline (Random Guess) line plot karein
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess (AUC = 0.50)')

# Graph ki settings
plt.xlabel('False Positive Rate (1 - Specificity)', fontsize=12)
plt.ylabel('True Positive Rate (Sensitivity / Recall)', fontsize=12)
plt.title('ROC Curve Comparison - Fraud Detection Pipeline', fontsize=14)
plt.legend(loc='lower right')
plt.grid(True)
plt.show()