# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HU3pWtsG-sjqADzyn7aHjp5lm4JNNyml
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# 1. Dummy Unlabeled Retail Data generate karna (25 behavioral features ke sath)
np.random.seed(42)
n_customers = 1000
data = {
    'Annual_Income': np.random.randint(20000, 120000, n_customers),
    'Purchase_Frequency': np.random.randint(1, 50, n_customers),
    'Total_Spend': np.random.uniform(100, 5000, n_customers),
}
# Mazeed 22 random columns taaki 20+ features ka requirement poora ho
for i in range(1, 23):
    data[f'Behavioral_Metric_{i}'] = np.random.randn(n_customers)

df_retail = pd.DataFrame(data)
print(f"Original Data Shape: {df_retail.shape} (1000 Customers, 25 Features)")

# 2. StandardScaler apply karna (Hamesha K-Means aur PCA se pehle lazmi hai)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_retail)

print("Standardization Complete! Mean ab 0 hai aur Standard Deviation 1.")

from sklearn.decomposition import PCA

# 1. PCA ko initialize karein (20+ columns ko 2 dimensions mein lane ke liye)
pca = PCA(n_components=2, random_state=42)

# 2. Scaled data par PCA apply karein
X_pca = pca.fit_transform(X_scaled)

# 3. Dataframe banayein taaki dekhne mein asani ho
df_pca = pd.DataFrame(data=X_pca, columns=['PC1', 'PC2'])

print("--- PCA Compression Complete ---")
print(f"Original Data Shape: {X_scaled.shape}")
print(f"Compressed Data Shape: {df_pca.shape}\n")

# Dekhein ke PCA ne kitna variance (information) retain kiya hai
variance_retained = pca.explained_variance_ratio_
print(f"PC1 Ne Information Capture Ki: {variance_retained[0]*100:.2f}%")
print(f"PC2 Ne Information Capture Ki: {variance_retained[1]*100:.2f}%")
print(f"Total Retained Information: {sum(variance_retained)*100:.2f}%")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

wcss = []
silhouette_scores = []
k_range = range(2, 9)

# 1. Alag alag K values ke liye K-Means chalayein
for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_pca)

    wcss.append(kmeans.inertia_) # Elbow method ke liye
    silhouette_scores.append(silhouette_score(X_pca, kmeans.labels_)) # Silhouette ke liye

# 2. Dono Graphs ko aik sath plot karein
plt.figure(figsize=(14, 5))

# Elbow Method Graph
plt.subplot(1, 2, 1)
plt.plot(k_range, wcss, marker='o', color='blue', linestyle='--')
plt.title('The Elbow Method', fontsize=12)
plt.xlabel('Number of Clusters (K)', fontsize=10)
plt.ylabel('WCSS (Inertia)', fontsize=10)
plt.grid(True)

# Silhouette Score Graph
plt.subplot(1, 2, 2)
plt.plot(k_range, silhouette_scores, marker='s', color='orange', linestyle='--')
plt.title('Silhouette Scores For Each K', fontsize=12)
plt.xlabel('Number of Clusters (K)', fontsize=10)
plt.ylabel('Silhouette Score', fontsize=10)
plt.grid(True)

plt.tight_layout()
plt.show()

# 1. K-Means ko final 3 clusters ke sath run karein
final_kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_pca['Cluster'] = final_kmeans.fit_transform(X_pca).argmin(axis=1) # Labels assign ho gaye

# Centroids (Markazi Points) nikalen
centroids = final_kmeans.cluster_centers_

# 2. Clusters ko graph par visually plot karein
plt.figure(figsize=(10, 7))

# Teeno clusters ko alag alag rangon mein display karna
colors = ['#FF4136', '#2ECC40', '#0074D9'] # Red, Green, Blue
cluster_names = ['Cluster A', 'Cluster B', 'Cluster C']

for i in range(3):
    cluster_data = df_pca[df_pca['Cluster'] == i]
    plt.scatter(cluster_data['PC1'], cluster_data['PC2'],
                c=colors[i], label=cluster_names[i], alpha=0.6, edgecolors='none', s=40)

# Centroids ko black 'X' mark se plot karna
plt.scatter(centroids[:, 0], centroids[:, 1],
            marker='X', s=250, c='black', label='Centroids')

plt.title('Final Customer Segmentation (PCA Space)', fontsize=14)
plt.xlabel('Principal Component 1 (PC1)', fontsize=12)
plt.ylabel('Principal Component 2 (PC2)', fontsize=12)
plt.legend(loc='best')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

# 1. Original Dataset mein vapas Clusters add karein taaki hum summary nikal sakein
df_retail['Target_Cluster'] = df_pca['Cluster']

# 2. Har cluster ka average behavior (Mean) calculate karein
cluster_summary = df_retail.groupby('Target_Cluster')[['Annual_Income', 'Purchase_Frequency', 'Total_Spend']].mean()

print("=== Clusters Ki Mathematical Mean Summary ===\n")
print(cluster_summary)
print("\n" + "="*50 + "\n")

# 3. Business Persona Translation Output print karein
print("=== FINAL BUSINESS PERSONAS REPORT ===\n")

for cluster_num in sorted(df_retail['Target_Cluster'].unique()):
    print(f"--- CLUSTER {cluster_num} ---")
    if cluster_num == 0:
        print("Persona Label: HIGH-VALUE ENGAGERS")
        print("Business Strategy: VIP Loyalty Program, exclusive previews, and premium rewards push karein.")
    elif cluster_num == 1:
        print("Persona Label: MID-TIER EXPLORERS")
        print("Business Strategy: Personalized discount coupons aur targeted email marketing se frequency barhayein.")
    else:
        print("Persona Label: LOW-ACTIVITY CHURN RISK")
        print("Business Strategy: Re-engagement campaigns aur heavy discount offer kar ke vapas laya jaye.")
    print("-" * 40)
    # bilal